spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kafka_helper
kafka:
  bootstrap:
    servers: localhost:9092
  helper:
    interface:
      url: http://localhost:8081
  topic:
    maintenance: common-maintenance-v1